name: learn-github-actions

on: push
jobs:
  gase:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          print(len(os.getenv('MY_VAR')))
        shell: python
        env:
          MY_VAR: ${{ secrets.WANDB_KEY }}
