name: learn-github-actions

on: push
jobs:
  gase:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
