name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]  # 執行這個 workflow 時
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hello
      run: |
        echo "this line show special symbols ${{github.repository}}."
    - name: run python code
      run: |
        pip install -r requirements.txt
        python ci.py
    - name: test shell
      run: |
	import os
	print(len(os.getenv('MY_VAR')))
      shell: python
      env:
        MY_VAR: ${{ secrets.WANDB_KEY }}
		
